name: Docker

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag'
        required: true

  workflow_call:
    inputs:
      tag:
        required: true
        type: string

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Determine version tag
        id: version-tag
        run: echo "tag=${{ github.event.inputs.tag || inputs.tag }}" >> "$GITHUB_OUTPUT"
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/ieasybooks/tahweel:latest
            ghcr.io/ieasybooks/tahweel:${{ steps.version-tag.outputs.tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
